# Use the official Node.js image as a base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set environment variables
# ENV PORT=3000
# ENV DATABASE_URL=postgres://postgres@localhost:5432/ecommerce
# ENV DATABASE_NAME=ecommerce
# ENV DATABASE_USER=dev
# ENV DATABASE_PASSWORD=
# ENV DATABASE_PORT=5432
# ENV DATABASE_HOST=host.docker.internal

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]